global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus: 9090" ]

  - job_name: "catalog-local"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "host.docker.internal:8081" ]

  - job_name: "inventory-local"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "host.docker.internal:8082" ]

  - job_name: "order-local"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "host.docker.internal:8083" ]
